/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRunRouteImport } from './routes/_authenticated/run'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedAdminChestsRouteImport } from './routes/_authenticated/admin.chests'
import { Route as AuthenticatedRacesIndexRouteImport } from './routes/_authenticated/races.index'
import { Route as AuthenticatedRacesIdRouteImport } from './routes/_authenticated/races.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunRoute = AuthenticatedRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminChestsRoute =
  AuthenticatedAdminChestsRouteImport.update({
    id: '/admin/chests',
    path: '/admin/chests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRacesIndexRoute = AuthenticatedRacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRacesIdRoute = AuthenticatedRacesIdRouteImport.update({
  id: '/races/$id',
  path: '/races/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/run': typeof AuthenticatedRunRoute
  '/shop': typeof AuthenticatedShopRoute
  '/admin/chests': typeof AuthenticatedAdminChestsRoute
  '/races/$id': typeof AuthenticatedRacesIdRoute
  '/races/': typeof AuthenticatedRacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/run': typeof AuthenticatedRunRoute
  '/shop': typeof AuthenticatedShopRoute
  '/admin/chests': typeof AuthenticatedAdminChestsRoute
  '/races/$id': typeof AuthenticatedRacesIdRoute
  '/races': typeof AuthenticatedRacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/run': typeof AuthenticatedRunRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/admin/chests': typeof AuthenticatedAdminChestsRoute
  '/_authenticated/races/$id': typeof AuthenticatedRacesIdRoute
  '/_authenticated/races/': typeof AuthenticatedRacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/friends'
    | '/home'
    | '/map'
    | '/profile'
    | '/run'
    | '/shop'
    | '/admin/chests'
    | '/races/$id'
    | '/races/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/friends'
    | '/home'
    | '/map'
    | '/profile'
    | '/run'
    | '/shop'
    | '/admin/chests'
    | '/races/$id'
    | '/races'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/friends'
    | '/_authenticated/home'
    | '/_authenticated/map'
    | '/_authenticated/profile'
    | '/_authenticated/run'
    | '/_authenticated/shop'
    | '/_authenticated/admin/chests'
    | '/_authenticated/races/$id'
    | '/_authenticated/races/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/run': {
      id: '/_authenticated/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof AuthenticatedRunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/chests': {
      id: '/_authenticated/admin/chests'
      path: '/admin/chests'
      fullPath: '/admin/chests'
      preLoaderRoute: typeof AuthenticatedAdminChestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/races/': {
      id: '/_authenticated/races/'
      path: '/races'
      fullPath: '/races/'
      preLoaderRoute: typeof AuthenticatedRacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/races/$id': {
      id: '/_authenticated/races/$id'
      path: '/races/$id'
      fullPath: '/races/$id'
      preLoaderRoute: typeof AuthenticatedRacesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRunRoute: typeof AuthenticatedRunRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedAdminChestsRoute: typeof AuthenticatedAdminChestsRoute
  AuthenticatedRacesIdRoute: typeof AuthenticatedRacesIdRoute
  AuthenticatedRacesIndexRoute: typeof AuthenticatedRacesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRunRoute: AuthenticatedRunRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedAdminChestsRoute: AuthenticatedAdminChestsRoute,
  AuthenticatedRacesIdRoute: AuthenticatedRacesIdRoute,
  AuthenticatedRacesIndexRoute: AuthenticatedRacesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
